version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  # Add reviewers
  reviewers:
    - "hqoapp/api-admins"
